### ISSUE TITLE
Failing to run, telling me it can't find the obsidian-rofi.py script

### ISSUE THREAD

**Issue by Archie-2021** [digitalsignalperson/obsidian-rofi-helper#1]
Hey, 
I just installed your plugin using BRAT and put the obsidian-rofi.py in ~/.local/bin directory and made it excitable. Then run this command using sxhkd. But running this give me an error telling me can't find the script. The command I run using sxhkd is this:

```
# Just switch Obsidian tabs
rofi -modi "obsidian:./obsidian-rofi.py" -show obsidian
```
I can't understand why the path is relative using "." . Can you please clarify a bit more on how I should run this script.

Can't take an screenshot but the error massage is this:
> Failed to execute: `./obsidian-rofi.py'
> Error: 'Failed to execute child process "./obsidian-rofi.py" (No such a file or directory)'

**Comment by digitalsignalperson** [comment]
the relative path would be that obsidian-rofi.py is in the current working directory that you are running the rofi command from. If you put it in ~/.local/bin and that's on the path, maybe it works with "obsidian:obsidian-rofi.py" ? Or maybe the full "obsidian:/home/name/.local/bin/obsidian-rofi.py" even?

Maybe my suggestion for a relative path is weird, I have a ~/scripts folder on my path, and a `,rofi.sh` currently like

```
#!/bin/bash

cd ~/scripts

# Use Ctrl+Tab to switch between windows and obsidian
~/git/rofi/build/rofi -modes "window,obsidian" -show window -show-icons -window-format "{c} {t}" -theme ~/scripts/rofi-theme.rasi -hover-select -modi "obsidian:./obsidian-rofi.py,window"

# KDE/kwin only, window highlight effect
qdbus org.kde.KWin /org/kde/KWin/HighlightWindow org.kde.KWin.HighlightWindow.highlightWindows "(" ")"
```

**Comment by Archie-2021** [comment]
> the relative path would be that obsidian-rofi.py is in the current working directory that you are running the rofi command from. If you put it in ~/.local/bin and that's on the path, maybe it works with "obsidian:obsidian-rofi.py" ? Or maybe the full "obsidian:/home/name/.local/bin/obsidian-rofi.py" even?
> 
> Maybe my suggestion for a relative path is weird, I have a ~/scripts folder on my path, and a `,rofi.sh` currently like
> 
> ```
> #!/bin/bash
> 
> cd ~/scripts
> 
> # Use Ctrl+Tab to switch between windows and obsidian
> ~/git/rofi/build/rofi -modes "window,obsidian" -show window -show-icons -window-format "{c} {t}" -theme ~/scripts/rofi-theme.rasi -hover-select -modi "obsidian:./obsidian-rofi.py,window"
> 
> # KDE/kwin only, window highlight effect
> qdbus org.kde.KWin /org/kde/KWin/HighlightWindow org.kde.KWin.HighlightWindow.highlightWindows "(" ")"
> ```

You were right and the issue was not using the fullpath, altho not that rofi shows up my obsidian tabs it does nothing when I hit enter on any of them.

**Comment by digitalsignalperson** [comment]
Check if you can use the URI commands on their own 

e.g. any file

```
obsidian://switch?vault=myvault&filename=Today.md
```

and with an id (what the rofi script uses)

```
obsidian://switch?vault=myvault&id=ea35ff567981fc58
```

You can find an id from your workspace.json, e.g.

```
          {
            "id": "ea35ff567981fc58",
            "type": "leaf",
            "state": {
              "type": "markdown",
              "state": {
                "file": "Today inbox.md",
                "mode": "source",
                "source": false
              }
            }
          },
```

**Comment by Archie-2021** [comment]
> Check if you can use the URI commands on their own
> 
> e.g. any file
> 
> ```
> obsidian://switch?vault=myvault&filename=Today.md
> ```
> 
> and with an id (what the rofi script uses)
> 
> ```
> obsidian://switch?vault=myvault&id=ea35ff567981fc58
> ```
> 
> You can find an id from your workspace.json, e.g.
> 
> ```
>           {
>             "id": "ea35ff567981fc58",
>             "type": "leaf",
>             "state": {
>               "type": "markdown",
>               "state": {
>                 "file": "Today inbox.md",
>                 "mode": "source",
>                 "source": false
>               }
>             }
>           },
> ```

```
Check if you can use the URI commands on their own

e.g. any file

```
obsidian://switch?vault=myvault&filename=Today.md
```

and with an id (what the rofi script uses)

```
obsidian://switch?vault=myvault&id=ea35ff567981fc58
```

You can find an id from your workspace.json, e.g.

```
          {
            "id": "ea35ff567981fc58",
            "type": "leaf",
            "state": {
              "type": "markdown",
              "state": {
                "file": "Today inbox.md",
                "mode": "source",
                "source": false
              }
            }
          },
		  
```
❯ obsidian://switch?vault=Vault-01&filename=_Home.md
[1] 434163
bash: obsidian://switch?vault=Vault-01: No such file or directory
[1]+  Exit 127                obsidian://switch?vault=Vault-01
```
Can it be a conflict with Advanced URI plugin I am using?

**Comment by digitalsignalperson** [comment]
I think it's because the uri isn't something bash understands as a command (similar to pasting a web URL in the shell).

Can you try `xdg-open obsidian://switch?vault=Vault-01&filename=_Home.md`

**Comment by Archie-2021** [comment]
> I think it's because the uri isn't something bash understands as a command (similar to pasting a web URL in the shell).
> 
> Can you try `xdg-open obsidian://switch?vault=Vault-01&filename=_Home.md`


Luke on obsidian discord change something in obsidian-rofi.py and it is working now.

https://discord.com/channels/686053708261228577/966134631625801729/1088840211892547606

```
#!/bin/python

import json
import sys
import os
from urllib.parse import quote
import subprocess

# Usage examples:
#   rofi -modi "obsidian:./obsidian-rofi.py" -show obsidian
#   rofi -modes combi -show combi -show-icons -combi-modes "window,obsidian:./obsidian-rofi.py"
#   rofi -modes "window,obsidian" -show window -show-icons -modi "window,obsidian:./obsidian-rofi.py"

# Set these two variables with your personal settings
vault_name = 'shiny'
vault_path = '/home/luke/shiny'


if 'ROFI_INFO' in os.environ:
    mid = os.environ['ROFI_INFO']
    name = quote(vault_name)
    uri = f'obsidian://switch?vault={name}&id={mid}'

    subprocess.call(["xdg-open", uri], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    sys.exit(0)


def leaf_indexes(data, indexes=None, depth=0):
    indexes = indexes or []
    if depth > 50:
        raise RecursionError
    if isinstance(data, dict):
        if data.get('type') == 'leaf':
            if data['state']['type'] in ['markdown', 'canvas', 'image', 'video', 'pdf']:
                if indexes[0] == 'main':
                    window_number = 0
                else:
                    window_number = indexes[2]
                
                yield indexes, data['id'], data['state']['state']['file']
        else:    
            for k, v in data.items():
                yield from leaf_indexes(v, indexes + [k], depth + 1)
    elif isinstance(data, list):
        for i, item in enumerate(data):
            yield from leaf_indexes(item, indexes + [i], depth + 1)


workspace_path = os.path.join(vault_path, '.obsidian/workspace.json')
with open(workspace_path) as f:
    data = json.load(f)

for index, mid, mfile in leaf_indexes(data):
    assert all([x == 'children' for x in index[1::2]])
    index_orig = index
    index = index.copy()
    
    tab = index.pop(-1)
    
    if index[0] == 'main':
        window = 0
        index = index[1:]
    else:
        window = 1 + index[2]
        index = index[3:]

    panes = index[1::2]
    
    n = 60
    mfile_str = mfile if len(mfile) < n else mfile[:n-3] + '...'
    window_str = '#' + str(window + 1)
    tab_str = '#' + str(tab + 1)
    name = f'{mfile_str:{n}}'
    name += '    '
    name += f'Window {window_str:3}  Tab {tab_str:3}'

    if len(panes) > 1:
        x = ', '.join(map(str, panes))
        name += f'  (pane {x})'

    # print(name)
    out = name + '\0info\x1f' + str(mid)
    print(out)
```

**Comment by digitalsignalperson** [comment]
That discord link isn't accessible to me.

It looks like 
```
import urllib
name = urllib.parse.quote(vault_name)
```
was changed to
```
from urllib.parse import quote
name = quote(vault_name)
```
which both do the same thing for me

**Comment by Archie-2021** [comment]
> That discord link isn't accessible to me.
> 
> It looks like
> 
> ```
> import urllib
> name = urllib.parse.quote(vault_name)
> ```
> 
> was changed to
> 
> ```
> from urllib.parse import quote
> name = quote(vault_name)
> ```
> 
> which both do the same thing for me

Yeah I think it is the line he was talking about.  I don't know much python so I don't understand the difference in importing it. All I know is that it didn't work with default version and it is working now with the modified version.
